name: vit_combo_box
description: "A collection of very flexible ComboBoxes/Dropdrop."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
    # -------------------

  assets:
    - packages/vit_combo_box/assets/expand.webp
