name: vit_combo_box
description: "A collection of very flexible ComboBoxes/Dropdrop."
version: 1.1.0
repository: https://github.com/TimeLord2010/vit_combo_box

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  assets:
    - packages/vit_combo_box/assets/expand.webp
